name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: HolliShake
          output: dist                 # <-- specify output folder

      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output              # branch to deploy to
          folder: dist                # deploy the dist folder
          clean: true
